// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"base_service/internal/api"
	"base_service/internal/api/grpc"
	"base_service/internal/api/http"
	"base_service/internal/application"
	"base_service/internal/infrastructure/persistent"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeContainer(db *sqlx.DB) *api.ApiContainer {
	userRepository := persistent.NewUserRepository(db)
	userHandler := app.NewUserHandler(userRepository)
	server := http.NewServer(userHandler)
	grpcServer := grpc.NewServer(userHandler)
	apiContainer := api.NewApiContainer(server, grpcServer)
	return apiContainer
}

// wire.go:

var container = wire.NewSet(api.NewApiContainer)

var apiSet = wire.NewSet(grpc.NewServer, http.NewServer)

var reposet = wire.NewSet(persistent.NewUserRepository)

var handlerSet = wire.NewSet(app.NewUserHandler)
