// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"base_service/internal/api/grpc"
	"base_service/internal/application"
	"base_service/internal/infrastructure/persistent"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeContainer(db *sqlx.DB) *grpc.Server {
	userRepository := persistent.NewUserRepository(db)
	userHandler := app.NewUserHandler(userRepository)
	server := grpc.NewServer(userHandler)
	return server
}

// wire.go:

var ApiSet = wire.NewSet(grpc.NewServer)

var Reposet = wire.NewSet(persistent.NewUserRepository)

var HandlerSet = wire.NewSet(app.NewUserHandler)
